version: "3.9"

services:
  db:
    build:
      context: ./Database
    image: db-container
    container_name: event-db
    environment:
      POSTGRES_USER: event_user
      POSTGRES_PASSWORD: event_password
      POSTGRES_DB: event_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: .
    image: backend-container
    container_name: event-backend
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://event_user:event_password@db:5432/event_db
      PORT: 3000
    ports:
      - "3000:3000"


volumes:
  pgdata:
